### PR TITLE
Thin client

### LINKED ISSUE #24: Use birdy as a user-friendly library to run WPS processes
birdy provides currently a command-line for WPS processes. It can also be extended to provide a library to run WPS processes. Users don't need to worry about the WPS protocol ... they just call a process like a normal python function.

See discussion:
https://github.com/bird-house/bird-house.github.io/issues/19

### PR DESCRIPTION
**Pull request by huard**
## Overview

This PR fixes #24 

Changes:

* Added native.py which provides a python native_client for WPS processes. 

## Related Issue / Discussion

* Authentication and tokens are not yet implemented. 

## Additional Information

https://github.com/bird-house/bird-house.github.io/issues/19

### CODE REVIEW

**Comment by huard** [comment]
One question I have is how to test it ? It needs a live server to work, so can we rely on an emu instance somewhere? 
Also, is there more code from your click client that can be reused ?

**Comment by cehbrecht** [comment]
@huard 
looks like fun :) 

Shortly tested. Fixed pep8, python3 compat and tests on travis. 

Codacy is not happy ... can be worked on later.

I will do a squash merge.

**Comment by cehbrecht** [comment]
done :)

**Comment by huard** [comment]
Thanks  !

**Comment by cehbrecht** [comment]
@huard 
We can invest a bit more in tests and provide "offline" tests with stored WPS responses (capabilities etc). When having online tests we could use "mouflon" ... pytest can check if the service is available and skip the test if not. Online service are not so reliable ... that troubles us in the owslib test-suite.

Here an example:
https://github.com/geopython/OWSLib/blob/master/tests/test_wms_getmap.py

Can't say about click yet ... I would have the same question :)

**Comment by huard** [comment]
Good to know, thanks !

**Pull request merged**
