### PR TITLE
added WPSResult class (#84)

### PR DESCRIPTION
**Pull request by cehbrecht**
## Overview

This PR contributes to issue #84.

Changes:

* Adds a new class `birdy.client.outputs.WPSResult` to represent WPS outputs.
* ... `convert_objects` argument has moved to `WPSResult.get_output()`.
* Updated tests.
* Added exceptions for WPS process status: running, failed, 
* Updated cp4cds notebook to use `WPSResult`.
* Skipped 52north test ... wps currently offline.

This is not the final answer to handle WPS outputs. Need to worry about naming conventions and status handling.

I haven't updated the other notebooks yet ...

## Related Issue / Discussion

#84

### CODE REVIEW

**Comment by cehbrecht** [comment]
@huard  ... but I would find it confusing that the return type changes just because we change the execution mode. Maybe we could extend the `namedtuple` with a lazy load for `async` mode?

Bye the way, we should not use `async` and `await` because they have become reserved keywords in Python 3.7.

The `async` mode should be set for each process execution. So, in `WPSClient` we can define the default ... but we may allow to overwrite the default somehow.

**Comment by cehbrecht** [comment]
... the other part of this PR is that I have moved `convert_objects` to `WPSResult.get_output(convert_object)`. The user can decide if it should be a reference or object ... you don't need to re-run the execution or define a new `WPSClient`.

**Comment by huard** [comment]
Hum. Could your WPSResult be a subclass of namedtuple then ? 
So the processes always return a namedtuple, it's just empty if it's in async mode, but there is a get method to fetch and process the outputs.

**Comment by cehbrecht** [comment]
I think the `collections.nametuple` is not meant to subclass. With Python 3.6  there is a new `typing.NameTuple` which might work ... but no support for 2.7.

I experimented with lazy-load ... not sure if I want to like this:

```
In [42]: from collections import namedtuple

In [43]: Output = namedtuple('Output', 'one, two')

In [44]: def gen_lazy_output(value):
    ...:     def output_func():
    ...:         return value
    ...:     return output_func
    ...: 

In [45]: o = Output._make([gen_lazy_output(1), gen_lazy_output(2)])

In [46]: o.one
Out[46]: <function __main__.gen_lazy_output.<locals>.output_func()>

In [47]: o.one()
Out[47]: 1
```

**Comment by huard** [comment]
Ok, so here is my suggestion. We create at runtime a Mixin class with WPSExecution that adds a `get` method that returns the output namedtuple. This gives access to users to all the info in the response if needed, and the convenience function of birdy to make the conversion to objects.

**Pull request merged**
