### PR TITLE
Tiff converter returns DataArray instead of Dataset.

### LINKED ISSUE #247: Tiff converter returns dataset instead of DataArray
## Description

Previously, TIFF converter returned DataArray, now returns Dataset. I think we could hard-code returning the band_data DataArray instead. 

Change introduced in 0.8.4 as a response to the deprecation of `xarray.open_rasterio`, but not thoroughly tested apparently. 

## Environment

* Birdy version used, if any:
* Python version, if any:
* Operating System:

## Steps to Reproduce

```
Paste the command(s) you ran and the output.
```

## Additional Information

Links to other issues or sources.

### PR DESCRIPTION
**Pull request by huard**
## Overview

This PR fixes #247 

Changes:

* Added ...

## Additional Information

Links to other issues or sources.

### CODE REVIEW

**Review by Zeitsperre — COMMENTED** [review]
Won't this change break support for multi-band GeoTIFFs? Is there a way to add a test for this here?

**Comment by huard** [comment]
Good point, do you have a multiband geotiff laying around ?

**Comment by huard** [comment]
Found one, and what happens is that bands are just a dimension of the DataArray.

**Comment by Zeitsperre** [comment]
> Found one, and what happens is that bands are just a dimension of the DataArray.

Ah, if that's the case, I'm relatively comfortable with this change. This behaviour has been around for a year, though, so it's possible that people are using. Would it be too cautious to ask for a second reviewer on this?

**Review by Zeitsperre — APPROVED** [review]
Approved for me, but let's wait for @cehbrecht before moving forward.

**Comment by huard** [comment]
No, it's been merged last March, see https://github.com/bird-house/birdy/pull/240/files

**Comment by Zeitsperre** [comment]
OK, if it was introduced two months ago (0.8.5), then it's clearly a regression. No need for Carsten to weigh in.

**Pull request merged**
