### PR TITLE
Fix emu #92

### PR DESCRIPTION
**Pull request by Zeitsperre**
## Overview

This PR fixes https://github.com/bird-house/emu/issues/92

Changes:

* Added a recipe for testing notebooks `test-nb`
* Moved some dependencies to requirements_dev.txt to ensure they are accessible to `test-nb`
* Added a `make test-nb` call to travis.yml to run the test ensemble for demo notebooks
* Changed a few requirements to be dependent on GitHub master as PyPI packages are not accessible

## Related Issue / Discussion
https://github.com/bird-house/emu/issues/92

## Additional Information
Many of the cells don't seem to be properly connecting with Birdy as installed from the environment.yml here. I also had to disable things like `progress=True`, as they were causing strange failures on URL connection. This may be related to other issues in Birdy (e.g. 

Links to other issues or sources.
https://github.com/bird-house/finch/issues/34
https://github.com/Ouranosinc/raven/pull/164

### CODE REVIEW

**Comment by Zeitsperre** [comment]
This is good to be reviewed. Tests are failing because the notebooks are failing.

**Comment by huard** [comment]
Good job. I think it's really valuable to have these notebooks tests integrated. As we can see, it's easy otherwise to let notebooks go stale. Maybe something we could fold into the cookie-cutter once it's more mature.

**Comment by huard** [comment]
@cehbrecht Do we want to fix the notebooks before merging ?
Also, open question: how could we handle async processes. At the moment I think they fail because pytest doesn't wait for them to complete.

**Comment by cehbrecht** [comment]
@Zeitsperre I was not aware of the `pytest-notebook` extension. Thanks for adding this :)

@Zeitsperre @huard Should we start with a `notebook/tests` folder and add/link notebooks to be tested? We could start with the agu notebook. The others can follow later ... if wanted. The `owslib-esgfwps` package does not need to be part of the normal birdy env. We could keep it just in the demo env.

**Comment by huard** [comment]
Sure. To be clear, I don't think we should write tests inside notebooks. We simply want to check that notebooks keep working after updates and are in sync with platforms and the software environment. If these notebooks have an educational value, then they should reside in the official docs as "examples".

**Comment by cehbrecht** [comment]
@Zeitsperre @huard should we move the non working notebooks to examples and try to fix the agu one? We can also do this in a next PR.

**Comment by huard** [comment]
Let's open another issue to fix the notebooks.

**Comment by Zeitsperre** [comment]
If it works for you both, I can set the `test-nb` to ignore exit code as a final change before merging. How do we feel about that?

**Comment by cehbrecht** [comment]
@Zeitsperre 
> I can set the test-nb to ignore exit code as a final change before merging

Sounds good. Feel free to merge. 

I can look at the notebooks to fix them in a follow-up PR.

**Pull request merged**
