### PR TITLE
added xarray to converters. 

### PR DESCRIPTION
**Pull request by huard**
## Overview

Changes:

* Added an xarray converter for netcdf mime types
* Converters are now lists tried in order until one works

### CODE REVIEW

**Comment by cehbrecht** [comment]
@huard what is the advantage of using xarray? Does xarray use the netcdf library?

**Comment by tomLandry** [comment]
Hello friends. For your information, xarray is squarely on OGC's radar since 6 months or so. They're still preparing a strategy for that. They're also aware of XClim and Finch birds. Don't hesitate to document xarray's advantages extensively. Sorry, can't help much there though. See OGC tech update: https://www.opengeospatial.org/blog/2969

**Comment by huard** [comment]
@cehbrecht xarray is a high level library for gridded computations. It reads netCDF and exposes methods that make data analysis a lot simpler than with stock numpy. Also, it comes with parallel processing capabilitie and automated plotting capability. I'm working on the Finch documentation, you will see examples of use shortly.

**Comment by cehbrecht** [comment]
@huard feel free to merge.

**Pull request merged**
