### PR TITLE
Add new converters for geodata formats

### PR DESCRIPTION
**Pull request by Zeitsperre**
## Overview

Changes:

* Added the OSG-officially recognized mimteypes for `geojson` and `geotiff` files to the supported mimetypes.
* re-enabled several converters for fiona/ogr data formats (untested)
* Added converters for rasterio/gdal data format (untested)
* Removed a duplicated supported mimteype (`application/octet-stream`) from `birdy.utils`.

## Related Issue / Discussion

https://github.com/radiantearth/stac-spec/pull/594

## Additional Information

Links to other issues or sources.

https://github.com/Ouranosinc/raven/pull/335
https://github.com/CSHS-CWRA/RavenPy/pull/39

### CODE REVIEW

**Review by cehbrecht — APPROVED** [review]

**Comment by cehbrecht** [comment]
@Zeitsperre do you want to add the optional dependencies to `requirements_extra.txt`?

**Review by huard — COMMENTED** [review]
Add tests for the new converters. 

Test integration using Emu. That is, create a new process, e.g. "geospatial", that returns outputs in various gis formats, and check that the WPSClient can convert them into the desired format. See tests/test_client.py for examples.

**Comment by Zeitsperre** [comment]
@huard @cehbrecht I've been trying to test the converters, but I'm not sure how they are triggered. Do you have any advice on how this is done?

**Comment by huard** [comment]
@Zeitsperre 
1. Start the emu server in the background.
2. Call the process through the WPSClient -> response
3. Get the results using `response.get(asobj=True)`

**Comment by Zeitsperre** [comment]
@huard Making changes on the Emu side now. This is not at all what I expect: 
image
I am completely mystified.

**Comment by huard** [comment]
Will look into it tomorrow.

**Comment by huard** [comment]
Can be tested with https://github.com/bird-house/emu/pull/108

**Pull request merged**
