### PR TITLE
Update GeoJSON mimetype

### PR DESCRIPTION
**Pull request by Zeitsperre**
## Overview

Changes:

* Modified mimetype from `application/vnd.geo+json` to `application/geo+json`.

## Related Issue / Discussion

Since the end of 2019, GeoJSON mimetype has been defined as `application/geo+json`. For more information see: https://tools.ietf.org/html/rfc7946.

## Additional Information

This fix is needed in order to address errors in Ouranosinc/raven (https://github.com/Ouranosinc/raven/issues/225).

### CODE REVIEW

**Comment by cehbrecht** [comment]
@Zeitsperre test fails ... but not related to this PR.

**Comment by cehbrecht** [comment]
This test wants a local emu wps, which is not available on travis:
```
tests/test_client.py::test_wps_with_language_arg FAILED 
```
We can mark it as *online* test, will be skipped by `make test`?

**Comment by Zeitsperre** [comment]
This is good to be merged.

**Comment by cehbrecht** [comment]
@Zeitsperre merged. Thanks :)

**Pull request merged**
