### PR TITLE
Namedtuple

### LINKED ISSUE #64: native client: how to return multiple values?
## Description

In the current *native* client implementation we either return a single value or a list of values. I would find it more descriptive to return a dictionary with: 
```
key=parameter identifier
value=parameter value
```

@huard @davidcaron 
What do you think?

Here a link from a quick google search:
https://stackoverflow.com/questions/354883/how-do-you-return-multiple-values-in-python

### PR DESCRIPTION
**Pull request by huard**
## Overview

This PR fixes #64

Changes:

* Outputs are namedtuple

### CODE REVIEW

**Comment by cehbrecht** [comment]
We worked in parallel on the same thing:
https://github.com/bird-house/birdy/blob/51639ec481395d37aea5d370f01e65c5ae4deaa8/birdy/client/base.py#L211

I would merge you PR and add some of my changes as a follow-up. Like the `make_identifier` (to guarantee a valid python name).

I would had a question ... but maybe that is already answered: We should always return a `namedtuple` ... even for a single output. Before we were using `delist` to return a single output directly.

**Comment by cehbrecht** [comment]
Fixed the `import` complain by codacy and got the `make test-all` working. There is an issue with complex outputs ... but not related to this PR. Should open an new ticket for this.

**Comment by huard** [comment]
For the single output, I initially kept delist, but changed it in the last commit, so you could say I'm not sure. It seems uniformity has an advantage, but I agree it's a bit heavy. I'm okay to revert back to delisting for single outputs.

**Comment by cehbrecht** [comment]
... I would currently prefer to keep it consistent with return a `namedtuple`. Otherwise it might be confusing. Maybe, as an idea for next steps, we could add a method `get_output` which always returns a single output ... but that could be `output[0]` as well.

**Comment by cehbrecht** [comment]
done. I will follow with my additions.

**Pull request merged**
