### PR TITLE
Object conversion is now nested and relies on extension

### PR DESCRIPTION
**Pull request by huard**
## Overview

Metalink and zip files previously only returned their internal files. This PR converts the files inside these objects as well, so the container is invisible if `asobj=True`.

Changes:

* The conversion logic is changed. Each converter has a priority attribute and it's ordered by the algorithm looking for appropriate converters. 

Based on `metalink` branch not yet merged, hence the conflicts with master.

### CODE REVIEW

**Comment by cehbrecht** [comment]
@huard I have troubles with the `metalink` package:
```
import metalink.download

  File "/Users/pingu/Documents/GitHub/birdhouse/birdy/src/metalink/metalink/download.py", line 2093
    except (socket.error, socket.herror, socket.gaierror, socket.timeout)::
                                                                          ^
SyntaxError: invalid syntax
```

Is it working with Python 3.6?

**Comment by huard** [comment]
Yes, but we should use the latest release, not master which has this typo in. Not clear how to do this in the environment.yml file. 

I've reported the typo but I've had no feedback from the maintainers. We might have to fork it.

**Comment by cehbrecht** [comment]
@huard I'm using a fork of `metalink` on birdhouse now.

**Comment by cehbrecht** [comment]
@huard merged :)

**Comment by huard** [comment]
I'm trying to get the darn metalink4 validation working on pywps... no real progress.

**Pull request merged**
